name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Setup Firefox
    # You may pin to the exact commit or the version.
    # uses: browser-actions/setup-firefox@be57d2b69141a920523254ad109a4008dcc73f04
      uses: browser-actions/setup-firefox@latest
      with:
    # The Firefox version to install and use. Examples: 84.0, 84.0.1, latest-esr
        firefox-version: latest
    - run: firefox --version
    - name: Test
      run: dotnet test --no-build --verbosity normal ./SpecFlowProject/SpecFlowProject.csproj

    
    
